VC.NONE <- "none"
VC.NEGATIVE <- "negative"
VC.POSITIVE <- "positive"

VC.LOW <- "low"
VC.INTERM <- "intermediate"
VC.HIGH <- "high"
VC.HIGH.INTERM <- "high-intermediate"
VC.ADVANCED <- "advanced"
VC.METASTATIC <- "metastatic"
